### ISSUE TITLE
Question: How is this different from Node Feature Extraction?

### ISSUE THREAD

**Issue by BradKML** [abhishekmaha23/RoleSim#1]
There are Node Feature libraries like:
- https://github.com/benedekrozemberczki/karateclub
- https://github.com/shenweichen/GraphEmbedding

How is RoleSim different?

**Comment by abhishekmaha23** [comment]
Karate Club is a multi-functional library with implementations of many other algorithms and approaches. 
The GraphEmbedding implementations appear to be handling a different scenario - my implementation is specifically for role detection and clustering in graph networks.

**Comment by BradKML** [comment]
@abhishekmaha23 is there a clear way of converting a graph embedding into a Role Detection/Clustering algorithm?

**Comment by abhishekmaha23** [comment]
That is actually interesting, but I don't think there's a clear answer. 
I believe it might depend on the form/nature of the embeddings? 
For example, in places where they're represented by vectors, clustering algorithms like k-means algorithms could work (unsupervised learning).

**Comment by BradKML** [comment]
@abhishekmaha23 unsupervised learning does sound interesting, but the issue is the vector space itself might have weird topologies, and different algorithms might respond differently.
https://www.researchgate.net/figure/a-Barbell-graph-B10-10-b-Roles-identiied-by-RolX-Latent-representations-in-R-2_fig3_316015951
https://www.sciencedirect.com/science/article/abs/pii/S0950705121001350#! and https://ars.els-cdn.com/content/image/1-s2.0-S0950705121001350-gr7.jpg
