### ISSUE TITLE
Alternative to RoleSim?

### ISSUE THREAD

**Issue by BradKML** [abhishekmaha23/RoleSim#2]
There are some articles that gives indices that are Separate from RoleSim.
https://github.com/benedekrozemberczki/karateclub/issues/66 and https://github.com/igraph/igraph/issues/1735

http://aimlab.cs.uoregon.edu/SMASH/web-portal/papers/TKDD13.pdf (page 12)

![image](https://user-images.githubusercontent.com/58927531/118906059-91868800-b94f-11eb-9332-0d9b02355042.png)

https://www.doc.ic.ac.uk/~wyu1/ppt/oral/sigir15.pdf

![image](https://user-images.githubusercontent.com/58927531/118906448-694b5900-b950-11eb-88f5-8a5807e781ad.png)

https://pdfs.semanticscholar.org/72c0/aa3b91756cebac6426deb8456892912e8bd9.pdf

![image](https://user-images.githubusercontent.com/58927531/118906531-8849eb00-b950-11eb-9ff5-7cbdaac4bec7.png)

- StructSim https://ieeexplore.ieee.org/document/9101469
- CentSim https://link.springer.com/chapter/10.1007/978-3-319-21042-1_10
- RoleSim++ https://d-nb.info/1184015848/34
- SimRank* https://link.springer.com/article/10.1007/s00778-018-0536-3

**Comment by BradKML** [comment]
http://ceur-ws.org/Vol-1353/paper_14.pdf
![image](https://user-images.githubusercontent.com/58927531/118915310-4f654280-b95f-11eb-8161-70dbaac57309.png)

https://arxiv.org/pdf/2002.08082.pdf
![image](https://user-images.githubusercontent.com/58927531/118915361-66a43000-b95f-11eb-9b2d-267662763c2f.png)

https://arxiv.org/pdf/1411.7228.pdf
![image](https://user-images.githubusercontent.com/58927531/118915417-7e7bb400-b95f-11eb-832c-6361e1adb4f6.png)

https://arxiv.org/pdf/1905.02354.pdf
![image](https://user-images.githubusercontent.com/58927531/118915477-9f440980-b95f-11eb-8f5e-35aeaa585ff6.png)

**Comment by BradKML** [comment]
- https://github.com/amir-f/delta-simrank
- https://github.com/rafguns/linkpred
- https://github.com/littleq0903/simrank
- https://github.com/pranavkulkarni/Link_prediction_social_network

**Comment by abhishekmaha23** [comment]
These are fascinating alternative algorithms!
I hadn't intended to make this a library, but am quite interested to see your contributions!
